chrisboulton/php-resque

lib/Resque.php
test/Resque/Tests/JobTest.php

Dequeue with args always removed first elements on queue when args matched.
Addresses issue #218 
Should replace pull request #221 from @SteveTherrien which is missing test for the bug.

Fix dequeueing with args

---

CHANGELOG.md
README.md
lib/Resque.php
lib/Resque/Job.php
lib/Resque/Job/DontCreate.php
test/Resque/Tests/EventTest.php

Add a `beforeEnqueue` hook that's called before a job is placed on a queue. You can cancel the creation of a job by throwing `Resque_Job_DontCreate` in a hook/plugin.
This is basically #199, but works slightly differently (throws an exception). The changes in #199 have issues if multiple plugins are listening on the one event, and don't include tests. 
The only thing I've not accounted for here is returning the not created status back to the caller. How do we want to handle this?
Ping @wedy & @danhunsaker

Add beforeEnqueue hook

---

lib/Resque/Redis.php
test/Resque/Tests/JobTest.php

I noticed that it was more or less required to reset the namespace to "resque" in order to pass tests.

Resolves chrisboulton/php-resque#145

---

lib/Resque/Job.php

The docblock for the $payload property in the Resque_Job class is object, which is inconsistent with the array type used for the corresponding constructor parameter. Other usage of the $payload property, such as in updateStatus(), indicate that array seems to be correct.

Corrected type in Resque_Job::$payload docblock

---

lib/Resque.php

Resque has the remove_queue command that removes the queue and all of the jobs. Added the method as removeQueue($queue) to php-resque.

Added remove_queue command from Resque

---

.travis.yml

A improvement in the tests execution adding PHP7 and HHVM, so we can know if something is breaking in those enviorment.
For now I add this versions to allow failures.

add PHP 7 and HHVM to TravisCI runtime

---

lib/Resque/Worker.php

OS X doesn't allow to use cli_set_process_title for security reasons and it keeps warning every cycle.

Fix OSX worker warning and cli_set_process_title

---

lib/Resque/Worker.php

Having `declare(ticks = 1)` inside `registerSigHandlers()` worked perfectly on PHP 5.6 but it doesn't on PHP 7.
I found it that moving the `declare(ticks = 1)` outside `registerSigHandlers()` solves the issue.
Could this please be merged and tagged ? :)
I found the idea of moving the `declare(ticks = 1)` in this PR: https://github.com/juriansluiman/SlmQueue/pull/175

POSIX signals are not working on PHP 7

---

lib/Resque/Worker.php

Presently, the logger just logs the primary error message with no stack trace of additional debugging information. Type casting the exception to a string gives a much efficient output  and enables better debugging.

More verbose logging if a Job throws an exception

---

lib/Resque/Redis.php

We should check to see if a user has chosen to not add a prefix and not append ":" if so.

Allow empty prefix

---

lib/Resque/Redis.php

- You can now provide a unix socket based redis connection: 
- `Resque::setBackend('unix:///path/to/redis.sock')`
- username/password/db in unix socket dsn currently unsupported: 
- This middle layer for Dsn parsing seemed too clunky for me to introduce user/pass/db parsing for unix sockets.

Add support for unprotected unix socket

---

bin/resque
lib/Resque.php

Return false if the fork function is unavailable

---

lib/Resque/Job.php
lib/Resque/Job/Factory.php
lib/Resque/Job/FactoryInterface.php
lib/Resque/JobInterface.php
test/Resque/Tests/EventTest.php
test/Resque/Tests/JobTest.php
test/Resque/Tests/TestCase.php

In order to make the Jobs injectable, I want to allow to delegate the responsibility of create new jobs to an independent factory. In that way, if I want to use Pimple, I can do so using a factory that will encapsulate access to Pimple to retrieve instances of `Resque_JobInterface`
I kept it as PSR-0 and I have added a couple of tests

Allowing to use a factory instead of manually instantiate the Jobs

---

lib/Resque/Redis.php
lib/Resque/RedisException.php
test/Resque/Tests/JobTest.php
test/Resque/Tests/RedisTest.php
test/Resque/Tests/TestCase.php

This is a first pass at changes to be loud whenever an error talking to Redis occurs, which should hopefully address some of the concerns in #228.
There's no way to differentiate between a connection related error and a general error returned from Redis (key is not of that data type, etc), so here we just throw a generic `Resque_RedisException` for anything we see.
Still need to do a full pass over all the Redis usage to see what behavioral changes we can expect as a result of this.

Surface Redis exceptions instead of silently returning false

---

.travis.yml

Moves away from using the existing matrix into a new one with the explicit combinations, only because with HHVM Redis is bundled and enabled by default.

Remove old PHP versions from test matrix, require PHP 7 and HHVM to pass as these are now officially supported

---

.travis.yml

While the current .travis.yml setup works, and the reasoning makes sense, it's far less readable than the previous configuration.  This suggested patch presents an alternative approach to the same result, which uses the matrix->exclude array to filter out invalid tests, instead of hard-coding every valid combination as the current file does.  This seems more readable, at least to me.

Use Matrix Exclude instead of hard-coded matrix

---

lib/Resque/Redis.php
test/Resque/Tests/JobTest.php
test/Resque/Tests/RedisTest.php

Rather than passing a fake/bad network address for these tests, I should probably mock Credis instead.

Use a mock to test correct redis exceptions are surfaced

---

composer.json
composer.lock

This introduces these changes: https://github.com/colinmollenhour/credis/compare/1.4...1.7
php-resque can't leverage some of the newer functionality out of the box (Redis Sentinel support), but if you want to leverage it you can do so by passing your own Credis instance into php-resque. Personally I haven't used the Sentinel support in Credis, we're currently using Predis as our php-resque Redis implementation.

Bump credis to 1.7

---

lib/Resque/Redis.php

`and` operator has different functionality (and priority) than `&&` operator (which is supposed to be there).
Even though it doesn't seem to cause harm in this case, it should still be fixed.
Thanks!

Resque_Redis: use `&&` rather than `and`

---

composer.json

I get a composer error while trying to require `resquebundle/resque` which uses `chrisboulton/php-resque`
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Can only install one of: psr/log[1.0.2, 1.0.0].
- Can only install one of: psr/log[1.0.0, 1.0.2].
- Can only install one of: psr/log[1.0.0, 1.0.2].
- chrisboulton/php-resque dev-master requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
- resquebundle/resque dev-master requires chrisboulton/php-resque dev-master -> satisfiable by chrisboulton/php-resque[dev-master].
- Installation request for resquebundle/resque dev-master -> satisfiable by resquebundle/resque[dev-master].
- Installation request for psr/log (locked at 1.0.2) -> satisfiable by psr/log[1.0.2].
```
This is resulted because I …

Composer locks due to psr/log dependency version
